platform :ios, '10.0'

## Without use_frameworks!

target 'Segment-GoogleAnalytics_Example' do
  # Use default subspec
  pod 'Segment-GoogleAnalytics', :path => '../'
  # Use default `GoogleIDFASupport` explicitly
  # pod 'Segment-GoogleAnalytics/GoogleIDFASupport', :path => '../'
  # Use only `Segment-GoogleAnalytics/Core`
  # pod 'Segment-GoogleAnalytics/Core', :path => '../'

  target 'Segment-GoogleAnalytics_Tests' do
    inherit! :search_paths

    pod 'OCMockito'
    pod 'Specta'
    pod 'Expecta'
  end
end

post_install do |installer|
installer.pods_project.build_configurations.each do |config|
  config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
end
end

## With use_frameworks!
# Use only `Segment-GoogleAnalytics/StaticLibWorkaround`

#use_frameworks!
#
#target 'Segment-GoogleAnalytics_Example' do
#  pod 'Segment-GoogleAnalytics/StaticLibWorkaround', :path => '../'
#  pod 'GoogleAnalytics'
#  pod 'GoogleIDFASupport'
#    
#  target 'Segment-GoogleAnalytics_Tests' do
#    inherit! :search_paths
#
#    pod 'OCMockito'
#    pod 'Specta'
#    pod 'Expecta'
#  end
#end
#
