target 'Segment-GoogleAnalytics_Example' do
  pod 'Segment-GoogleAnalytics', :path => '../'

  target 'Segment-GoogleAnalytics_Tests' do
    inherit! :search_paths

    pod 'OCMockito'
    pod 'Specta'
    pod 'Expecta'
  end
end
